In [20]:
import tensorflow as tf

NUM_CORES = 6

config = tf.ConfigProto(
    inter_op_parallelism_threads=NUM_CORES,
    intra_op_parallelism_threads=NUM_CORES
)

lhs = tf.placeholder(tf.float32, shape=(2, 2))
rhs = tf.placeholder(tf.float32, shape=(2, 2))
op = tf.matmul(lhs, rhs)

with tf.Session(config=config) as session:
    session.run(tf.initialize_all_variables())
    for i in range(10):
        retval = session.run(
            op, 
            feed_dict={
                lhs: [[i, i + 1],[i + 2, i + 3]], 
                rhs: [[i + 3, i + 2],[i, i + 1]]
            }
        )
        print retval



[[ 0.  1.]
 [ 6.  7.]]
[[  6.   7.]
 [ 16.  17.]]
[[ 16.  17.]
 [ 30.  31.]]
[[ 30.  31.]
 [ 48.  49.]]
[[ 48.  49.]
 [ 70.  71.]]
[[ 70.  71.]
 [ 96.  97.]]
[[  96.   97.]
 [ 126.  127.]]
[[ 126.  127.]
 [ 160.  161.]]
[[ 160.  161.]
 [ 198.  199.]]
[[ 198.  199.]
 [ 240.  241.]]
